version: "3.3"
services:
  postgres:
    image: postgis/postgis:13
    container_name: 'postgis-digiroad2'
    environment:
      POSTGRES_USER: masterUser
      POSTGRES_PASSWORD: masterUser
      POSTGRES_DB: masterUser
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
#    command: ["postgres", "-c", "log_statement=all"]
  cacheDatabaseMemcache:
    image: memcached:1.6.6-alpine
    ports:
      - 11211:11211
    command: "-I 134M -m 500" # AWS

volumes:
  data: